# Generated by Django 4.0 on 2022-04-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakdowncategory',
            options={'managed': True},
        ),
    ]
