# Generated by Django 4.0 on 2022-04-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_breakdowncategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakdowncategory',
            options={},
        ),
    ]
