# Generated by Django 4.0 on 2022-04-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_surveybreakdown_surveybreakdown_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveybreakdown',
            name='surveybreakdown_category',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
