# Generated by Django 4.0 on 2022-04-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_surveybreakdown_surveybreakdown_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerDuration',
        ),
    ]
