# Generated by Django 4.0 on 2022-04-08 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_delete_answerduration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_duration', models.DurationField()),
                ('answer_status', models.BooleanField(null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.question')),
                ('surveyinstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.surveyinstance')),
            ],
        ),
    ]
