# Generated by Django 4.0 on 2022-04-12 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('data', '0007_answerduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_reminder_date',
            field=models.DateField(null=True, verbose_name='Reminder Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='entity',
            field=models.ManyToManyField(to='data.Entity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_start_date',
            field=models.DateField(null=True, verbose_name='Due Date'),
        ),
    ]
