# Generated by Django 4.0 on 2022-04-12 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_surveybreakdown_survey_reminder_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveybreakdown',
            old_name='survey_reminder_date',
            new_name='surveybreakdown_reminder_date',
        ),
    ]
