# Generated by Django 4.0 on 2022-04-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_remove_survey_survey_reminder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveybreakdown',
            name='surveybreakdown_reminder_date',
        ),
    ]
