# Generated by Django 4.0 on 2022-04-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_surveybreakdown_surveybreakdown_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinstance',
            name='survey_reminder_date',
            field=models.DateField(null=True),
        ),
    ]
