# Generated by Django 4.0 on 2022-04-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_surveyinstance_survey_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answerinteger',
            name='answer_integer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Short Text', 'Short Text'), ('Long Text', 'Long Text'), ('File', 'File'), ('Whole Number', 'Whole Number'), ('Decimal Number', 'Decimal Number'), ('Date', 'Date')], default='text', max_length=20),
        ),
    ]
