# Generated by Django 4.0 on 2022-04-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_survey_survey_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
