# Generated by Django 4.0 on 2022-04-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_survey_survey_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_status',
            field=models.BooleanField(default=True, verbose_name='Is this Church active?'),
        ),
        migrations.AlterField(
            model_name='entitygroup',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.entity', verbose_name='Church'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='entity',
            field=models.ManyToManyField(to='data.Entity', verbose_name='Church'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='site_permission',
            field=models.CharField(choices=[('user', 'user'), ('centalteam', 'centalteam'), ('entity', 'entity'), ('org', 'org'), ('sa', 'sa')], default='user', max_length=30),
        ),
        migrations.AlterField(
            model_name='survey',
            name='entity',
            field=models.ManyToManyField(blank=True, help_text='You can select multiple entities by using the ctrl or shift key. To select all press ctrl & a', through='data.SurveyEntity', to='data.Entity', verbose_name='Select churches'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_active',
            field=models.BooleanField(default=True, verbose_name='Survey active'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_breakdown_allowed',
            field=models.BooleanField(default=True, verbose_name='Allow church to segment this survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_entity_to_set_times',
            field=models.BooleanField(default=False, verbose_name='Allow entity to set dates, interval and occurnces'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_name',
            field=models.CharField(max_length=200, verbose_name='Survey name'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_start_date',
            field=models.DateField(null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='surveyentity',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.entity', verbose_name='Church'),
        ),
    ]
