# Generated by Django 4.0 on 2022-04-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_remove_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
