# Generated by Django 4.0 on 2022-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_remove_survey_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.CharField(max_length=200, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Short Text', 'Short Text'), ('Long Text', 'Long Text'), ('File', 'File'), ('Whole Number', 'Whole Number'), ('Decimal Number', 'Decimal Number'), ('Date', 'Date')], default='text', max_length=20, verbose_name='Type'),
        ),
    ]
